---
- name: redemarrage des services
  hosts: all

  tasks:
  - name: redemarrage de mongoDB
    systemd: 
      name: mongod
      state: restarted
      daemon_reload: yes
      when: service_status.stat.exists
  
  - name: redemarrage de rabbitmq
    systemd: 
      name: rabbitmq
      state: restarted
      daemon_reload: yes
      when: service_status.stat.exists

  - name: redemarrage de redis
    systemd: 
      name: redis
      state: restarted
      daemon_reload: yes
      when: service_status.stat.exists

  - name: redemarrage de elasticsearch
    systemd: 
      name: elasticsearch
      state: restarted
      daemon_reload: yes
      when: service_status.stat.exists
...