---
- name: restart des services
  hosts: all

  tasks:
  - name: arret de mongoDB
    ansible.builtin.systemd: 
      name: mongod
      state: stopped
  
  - name: arret de rabbitmq
    ansible.builtin.systemd: 
      name: rabbitmq
      state: stopped
  
  - name: arret de redis
    ansible.builtin.systemd: 
      name: redis
      state: stopped

  - name: arret de elasticsearch
    ansible.builtin.systemd: 
      name: elasticsearch
      state: stopped

  - name: démarrage de mongoDB
    ansible.builtin.systemd: 
      name: mongod
      state: started
  
  - name: démarrage de rabbitmq
    ansible.builtin.systemd: 
      name: rabbitmq
      state: started
  
  - name: démarrage de redis
    ansible.builtin.systemd: 
      name: redis
      state: started

  - name: démarrage de elasticsearch
    ansible.builtin.systemd: 
      name: elasticsearch
      state: started
...